"""initial schema: 17 tables incl. the participants consent guards

Revision ID: 6d2b1d597c6d
Revises: 
Create Date: 2026-09-24 10:25:01.851905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2b1d597c6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name_bn', sa.String(length=160), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('twofa_enabled', sa.Boolean(), nullable=False),
    sa.Column('twofa_secret', sa.String(length=512), nullable=True),
    sa.Column('recovery_codes', sa.String(length=2048), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_users_email'), ['email'], unique=True)

    op.create_table('backups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('database', 'uploads', 'full', name='backupkind'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('running', 'ok', 'failed', name='backupstatus'), nullable=False),
    sa.Column('offsite_ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backups_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_backups_expires_at'), ['expires_at'], unique=False)

    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('subject', sa.String(length=240), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('status', sa.Enum('new', 'read', 'replied', 'closed', name='messagestatus'), nullable=False),
    sa.Column('replied_at', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_messages_ip'), ['ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_messages_status'), ['status'], unique=False)
        batch_op.create_index('ix_contact_messages_status_created', ['status', 'created_at'], unique=False)

    op.create_table('faqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('question_bn', sa.String(length=400), nullable=False),
    sa.Column('answer_bn', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faqs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faqs_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_faqs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_faqs_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_faqs_sort_order'), ['sort_order'], unique=False)

    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('was_successful', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=48), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_ip'), ['ip'], unique=False)
        batch_op.create_index('ix_login_attempts_ip_created', ['ip', 'created_at'], unique=False)

    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('name_bn', sa.String(length=160), nullable=False),
    sa.Column('name_en', sa.String(length=160), nullable=True),
    sa.Column('education', sa.Enum('HSC', 'Diploma', 'Degree', 'Honours', 'Other', name='education'), nullable=False),
    sa.Column('occupation_before', sa.String(length=80), nullable=True),
    sa.Column('outcome_type', sa.Enum('employment', 'freelancing', 'further_study', 'business', 'teaching', 'other', name='outcometype'), nullable=True),
    sa.Column('outcome_text', sa.Text(), nullable=True),
    sa.Column('quote_bn', sa.Text(), nullable=True),
    sa.Column('quote_consented', sa.Boolean(), nullable=False),
    sa.Column('batch', sa.SmallInteger(), nullable=False),
    sa.Column('consent_publication', sa.Boolean(), nullable=False),
    sa.Column('consent_date', sa.Date(), nullable=True),
    sa.Column('consent_source', sa.Enum('written_form', 'sms', 'email', 'verbal_witnessed', 'programme_terms', name='consentsource'), nullable=True),
    sa.Column('consent_notes', sa.Text(), nullable=True),
    sa.Column('consent_withdrawn_at', sa.DateTime(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('search_blob', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('is_published = 0 OR (consent_publication = 1 AND consent_date IS NOT NULL)', name='ck_participants_publish_requires_consent'),
    sa.CheckConstraint('quote_bn IS NULL OR quote_consented = 1', name='ck_participants_quote_requires_permission'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participants_batch'), ['batch'], unique=False)
        batch_op.create_index(batch_op.f('ix_participants_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_participants_education'), ['education'], unique=False)
        batch_op.create_index('ix_participants_published_consent', ['is_published', 'consent_publication'], unique=False)
        batch_op.create_index(batch_op.f('ix_participants_search_blob'), ['search_blob'], unique=False)
        batch_op.create_index(batch_op.f('ix_participants_slug'), ['slug'], unique=True)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=96), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.Enum('string', 'int', 'bool', 'json', name='settingvaluetype'), nullable=False),
    sa.Column('group', sa.String(length=48), nullable=False),
    sa.Column('label_bn', sa.String(length=200), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_settings_key')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_settings_group'), ['group'], unique=False)
        batch_op.create_index(batch_op.f('ix_settings_key'), ['key'], unique=True)

    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label_bn', sa.String(length=160), nullable=False),
    sa.Column('value_bn', sa.String(length=64), nullable=True),
    sa.Column('value_num', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unit_bn', sa.String(length=32), nullable=True),
    sa.Column('source', sa.Enum('manual', 'computed', name='statsource'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stats_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stats_display_order'), ['display_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_stats_key'), ['key'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_actor_created', ['actor_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('consent_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('granted', 'withdrawn', 'updated', name='consentaction'), nullable=False),
    sa.Column('source', sa.Enum('written_form', 'sms', 'email', 'verbal_witnessed', 'programme_terms', name='consentsource'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_events_participant_id'), ['participant_id'], unique=False)

    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('title_bn', sa.String(length=240), nullable=False),
    sa.Column('summary_bn', sa.Text(), nullable=True),
    sa.Column('duration_days', sa.SmallInteger(), nullable=True),
    sa.Column('duration_hours', sa.SmallInteger(), nullable=True),
    sa.Column('hours_per_day', sa.SmallInteger(), nullable=True),
    sa.Column('certification_note_bn', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_slug'), ['slug'], unique=True)

    op.create_table('imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('participants', name='importkind'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('success_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('error_report_path', sa.String(length=500), nullable=True),
    sa.Column('is_dry_run', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('dry_run', 'committed', 'failed', name='importstatus'), nullable=False),
    sa.Column('column_map', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('imports', schema=None) as batch_op:
        batch_op.create_index('ix_imports_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_imports_created_at'), ['created_at'], unique=False)

    op.create_table('media_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('mime', sa.String(length=96), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('image', 'video_link', name='mediakind'), nullable=False),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('alt_bn', sa.String(length=300), nullable=True),
    sa.Column('caption_bn', sa.String(length=300), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_used_count'), ['used_count'], unique=False)

    op.create_table('course_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title_bn', sa.String(length=200), nullable=False),
    sa.Column('description_bn', sa.Text(), nullable=True),
    sa.Column('hours', sa.SmallInteger(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('icon_slug', sa.String(length=48), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_modules_course_id'), ['course_id'], unique=False)
        batch_op.create_index('ix_course_modules_course_order', ['course_id', 'sort_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_modules_created_at'), ['created_at'], unique=False)

    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('name_bn', sa.String(length=240), nullable=False),
    sa.Column('name_en', sa.String(length=240), nullable=True),
    sa.Column('role_bn', sa.String(length=120), nullable=True),
    sa.Column('address_bn', sa.Text(), nullable=True),
    sa.Column('contact_phone', sa.String(length=40), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('map_url', sa.String(length=500), nullable=True),
    sa.Column('description_bn', sa.Text(), nullable=True),
    sa.Column('logo_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['logo_id'], ['media_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_institutions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_institutions_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_institutions_slug'), ['slug'], unique=True)

    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('title_bn', sa.String(length=200), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=True),
    sa.Column('nav_label_bn', sa.String(length=80), nullable=True),
    sa.Column('show_in_nav', sa.Boolean(), nullable=False),
    sa.Column('meta_description_bn', sa.String(length=320), nullable=True),
    sa.Column('og_image_id', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['og_image_id'], ['media_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_is_published'), ['is_published'], unique=False)
        batch_op.create_index('ix_pages_nav_order', ['show_in_nav', 'sort_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_pages_sort_order'), ['sort_order'], unique=False)

    op.create_table('page_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_sections_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_sections_page_id'), ['page_id'], unique=False)
        batch_op.create_index('ix_page_sections_page_order', ['page_id', 'sort_order'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_sections', schema=None) as batch_op:
        batch_op.drop_index('ix_page_sections_page_order')
        batch_op.drop_index(batch_op.f('ix_page_sections_page_id'))
        batch_op.drop_index(batch_op.f('ix_page_sections_created_at'))

    op.drop_table('page_sections')
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pages_sort_order'))
        batch_op.drop_index(batch_op.f('ix_pages_slug'))
        batch_op.drop_index('ix_pages_nav_order')
        batch_op.drop_index(batch_op.f('ix_pages_is_published'))
        batch_op.drop_index(batch_op.f('ix_pages_created_by'))
        batch_op.drop_index(batch_op.f('ix_pages_created_at'))

    op.drop_table('pages')
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institutions_slug'))
        batch_op.drop_index(batch_op.f('ix_institutions_created_by'))
        batch_op.drop_index(batch_op.f('ix_institutions_created_at'))

    op.drop_table('institutions')
    with op.batch_alter_table('course_modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_modules_created_at'))
        batch_op.drop_index('ix_course_modules_course_order')
        batch_op.drop_index(batch_op.f('ix_course_modules_course_id'))

    op.drop_table('course_modules')
    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_items_used_count'))
        batch_op.drop_index(batch_op.f('ix_media_items_created_at'))

    op.drop_table('media_items')
    with op.batch_alter_table('imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imports_created_at'))
        batch_op.drop_index('ix_imports_created')

    op.drop_table('imports')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_slug'))
        batch_op.drop_index(batch_op.f('ix_courses_created_by'))
        batch_op.drop_index(batch_op.f('ix_courses_created_at'))

    op.drop_table('courses')
    with op.batch_alter_table('consent_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_events_participant_id'))
        batch_op.drop_index(batch_op.f('ix_consent_events_created_at'))

    op.drop_table('consent_events')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_entity')
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index('ix_audit_logs_actor_created')
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stats_key'))
        batch_op.drop_index(batch_op.f('ix_stats_display_order'))
        batch_op.drop_index(batch_op.f('ix_stats_created_at'))

    op.drop_table('stats')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_key'))
        batch_op.drop_index(batch_op.f('ix_settings_group'))
        batch_op.drop_index(batch_op.f('ix_settings_created_at'))

    op.drop_table('settings')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participants_slug'))
        batch_op.drop_index(batch_op.f('ix_participants_search_blob'))
        batch_op.drop_index('ix_participants_published_consent')
        batch_op.drop_index(batch_op.f('ix_participants_education'))
        batch_op.drop_index(batch_op.f('ix_participants_created_at'))
        batch_op.drop_index(batch_op.f('ix_participants_batch'))

    op.drop_table('participants')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_login_attempts_ip_created')
        batch_op.drop_index(batch_op.f('ix_login_attempts_ip'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_email'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_created_at'))

    op.drop_table('login_attempts')
    with op.batch_alter_table('faqs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faqs_sort_order'))
        batch_op.drop_index(batch_op.f('ix_faqs_is_active'))
        batch_op.drop_index(batch_op.f('ix_faqs_created_at'))
        batch_op.drop_index(batch_op.f('ix_faqs_category'))

    op.drop_table('faqs')
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_contact_messages_status_created')
        batch_op.drop_index(batch_op.f('ix_contact_messages_status'))
        batch_op.drop_index(batch_op.f('ix_contact_messages_ip'))
        batch_op.drop_index(batch_op.f('ix_contact_messages_created_at'))

    op.drop_table('contact_messages')
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backups_expires_at'))
        batch_op.drop_index(batch_op.f('ix_backups_created_at'))

    op.drop_table('backups')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_email'))
        batch_op.drop_index(batch_op.f('ix_admin_users_created_at'))

    op.drop_table('admin_users')
    # ### end Alembic commands ###
