"""front end content moves into the database

Revision ID: c876e5ccb600
Revises: 024e6c9f803a

WHAT AND WHY
    `frontend/src/data/mockData.ts` held 94 KB of TypeScript constants — the course
    phases, the 11 training tools, the cohort's work, the trainers, the 13 modules and
    the register. The front end rendered all of it and the CMS could reach none of it,
    so "edit it in the admin" changed nothing on the site.

    This revision adds the four tables that had no home (`course_phases`,
    `training_tools`, `batch_works`, `instructors`) and the columns the four existing
    tables were missing. §10's table count goes from 17 to 21.

    THE THREE JSON COLUMNS GET A SERVER DEFAULT, and that is not decoration: SQLite
    cannot add a NOT NULL column without one, and the 13 module rows already exist. The
    default is only for the ALTER — the model still supplies `[]` on insert.

    THE FOREIGN KEYS ARE NAMED. Autogenerate rendered them as `None`, which works for
    `create` and fails for the `downgrade`, and a migration that cannot be reversed is
    a migration nobody will run.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c876e5ccb600'
down_revision = '024e6c9f803a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=48), nullable=False),
    sa.Column('phase_number_bn', sa.String(length=32), nullable=False),
    sa.Column('title_bn', sa.String(length=200), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=True),
    sa.Column('hours_bn', sa.String(length=48), nullable=True),
    sa.Column('days_bn', sa.String(length=96), nullable=True),
    sa.Column('objective_bn', sa.Text(), nullable=True),
    sa.Column('tools_count_bn', sa.String(length=48), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_phases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_phases_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_phases_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_phases_slug'), ['slug'], unique=True)

    op.create_table('training_tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sl_no_bn', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('category_bn', sa.String(length=200), nullable=True),
    sa.Column('description_bn', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_tools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_tools_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_tools_created_by'), ['created_by'], unique=False)

    op.create_table('batch_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('kind', sa.Enum('video', 'poster', 'music', 'document', 'gallery', name='workkind'), nullable=False),
    sa.Column('kind_label_bn', sa.String(length=48), nullable=True),
    sa.Column('title_bn', sa.String(length=240), nullable=False),
    sa.Column('meta_bn', sa.String(length=240), nullable=True),
    sa.Column('duration_or_pages_bn', sa.String(length=64), nullable=True),
    sa.Column('description_bn', sa.Text(), nullable=True),
    sa.Column('team_or_creator_bn', sa.String(length=240), nullable=True),
    sa.Column('date_bn', sa.String(length=96), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=24), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('batch', sa.SmallInteger(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['media_id'], ['media_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batch_works', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_works_batch'), ['batch'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_works_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_works_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_works_slug'), ['slug'], unique=True)

    op.create_table('instructors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('slide_number_bn', sa.String(length=16), nullable=True),
    sa.Column('slide_number_en', sa.String(length=16), nullable=True),
    sa.Column('status', sa.Enum('current', 'former', name='instructorstatus'), nullable=False),
    sa.Column('status_label_bn', sa.String(length=32), nullable=True),
    sa.Column('tenure_bn', sa.String(length=120), nullable=True),
    sa.Column('name_bn', sa.String(length=160), nullable=False),
    sa.Column('name_en', sa.String(length=160), nullable=True),
    sa.Column('designation_bn', sa.String(length=200), nullable=True),
    sa.Column('credentials_bn', sa.String(length=240), nullable=True),
    sa.Column('academic_bn', sa.String(length=240), nullable=True),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('quote_bn', sa.Text(), nullable=True),
    sa.Column('bio_bn', sa.Text(), nullable=True),
    sa.Column('specialties_bn', sa.JSON(), nullable=False),
    sa.Column('contributions_bn', sa.JSON(), nullable=False),
    sa.Column('hours_taught_bn', sa.String(length=48), nullable=True),
    sa.Column('batch_bn', sa.String(length=48), nullable=True),
    sa.Column('students_trained_bn', sa.String(length=48), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['photo_id'], ['media_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instructors_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_instructors_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_instructors_slug'), ['slug'], unique=True)
        batch_op.create_index('ix_instructors_status_order', ['status', 'sort_order'], unique=False)

    with op.batch_alter_table('course_modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phase_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('title_en', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('code_bn', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('code', sa.String(length=24), nullable=True))
        batch_op.add_column(sa.Column('hours_bn', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('duration_bn', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('weeks_bn', sa.String(length=48), nullable=True))
        batch_op.add_column(sa.Column('days_range_bn', sa.String(length=96), nullable=True))
        batch_op.add_column(sa.Column('tools', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('topics_bn', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('learning_outcomes_bn', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('summary_bn', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('practical_deliverable_bn', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_course_modules_phase_id'), ['phase_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_course_modules_phase_id', 'course_phases', ['phase_id'], ['id'], ondelete='SET NULL'
        )

    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_participants_institution_id', 'institutions', ['institution_id'], ['id'],
            ondelete='SET NULL'
        )

    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context_bn', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.drop_column('context_bn')

    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_constraint('fk_participants_institution_id', type_='foreignkey')
        batch_op.drop_column('institution_id')

    with op.batch_alter_table('course_modules', schema=None) as batch_op:
        batch_op.drop_constraint('fk_course_modules_phase_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_course_modules_phase_id'))
        batch_op.drop_column('practical_deliverable_bn')
        batch_op.drop_column('summary_bn')
        batch_op.drop_column('learning_outcomes_bn')
        batch_op.drop_column('topics_bn')
        batch_op.drop_column('tools')
        batch_op.drop_column('days_range_bn')
        batch_op.drop_column('weeks_bn')
        batch_op.drop_column('duration_bn')
        batch_op.drop_column('hours_bn')
        batch_op.drop_column('code')
        batch_op.drop_column('code_bn')
        batch_op.drop_column('title_en')
        batch_op.drop_column('phase_id')

    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.drop_index('ix_instructors_status_order')
        batch_op.drop_index(batch_op.f('ix_instructors_slug'))
        batch_op.drop_index(batch_op.f('ix_instructors_created_by'))
        batch_op.drop_index(batch_op.f('ix_instructors_created_at'))

    op.drop_table('instructors')
    with op.batch_alter_table('batch_works', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_works_slug'))
        batch_op.drop_index(batch_op.f('ix_batch_works_created_by'))
        batch_op.drop_index(batch_op.f('ix_batch_works_created_at'))
        batch_op.drop_index(batch_op.f('ix_batch_works_batch'))

    op.drop_table('batch_works')
    with op.batch_alter_table('training_tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_tools_created_by'))
        batch_op.drop_index(batch_op.f('ix_training_tools_created_at'))

    op.drop_table('training_tools')
    with op.batch_alter_table('course_phases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_phases_slug'))
        batch_op.drop_index(batch_op.f('ix_course_phases_created_by'))
        batch_op.drop_index(batch_op.f('ix_course_phases_created_at'))

    op.drop_table('course_phases')
    # ### end Alembic commands ###
