#!/usr/bin/env python3
"""Ban-list gate — enforces the rules a CSS build cannot see. plan.md §7.6, §12.2.

    python tools/check-bans.py [paths...]

Exits 0 when clean, 1 on any violation. Wired into `npm run bans`, `ci.yml` and
`deploy.sh`'s blocking job 1 (§17.5 calls this "the ban-list check").

WHY THIS EXISTS SEPARATELY FROM check-css.py
    check-css.py polices the COMPILED stylesheet. It cannot see:
      - a banned word in Bangla or English copy
      - emoji used as iconography
      - a class that silently failed to compile
      - `|safe` on content that came from a form
      - a `district` column creeping back into a model
    Those live in templates and Python, so they are checked there.

WHAT IS SCANNED
    app/  assets/  *.py at the root          — the shipped surface
WHAT IS NOT
    plan.md, EXECUTION-PLAN.md, docs/, tools/, design-src/, node_modules/, .venv/
    Those files DEFINE the rules, so they necessarily contain the banned words.

ESCAPE HATCH
    A line ending in `check-bans:ignore` is skipped.
    A file whose first five lines contain `check-bans:ignore-file` is skipped.
    Both must state a reason in the same comment. Use them for real exceptions
    (a test fixture that must contain a banned string), never for convenience.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path

# ─────────────────────────────────────────────────────────────────────────────
# Rule set
# ─────────────────────────────────────────────────────────────────────────────

# Emoji as iconography (§7.6) — icons come from one inlined SVG sprite.
# Ranges cover emoji, dingbats, variation selectors and regional indicators.
# The Bengali block (U+0980–09FF) is deliberately outside every range.
EMOJI_RE = re.compile(
    "["
    "\U0001F000-\U0001FAFF"  # pictographs, emoticons, symbols, flags
    "\U0001F1E6-\U0001F1FF"  # regional indicators
    "\u2600-\u27BF"          # misc symbols + dingbats
    "\u2B00-\u2BFF"          # arrows and geometric symbols
    "\uFE0E\uFE0F"           # variation selectors — the "emoji presentation" toggle
    "\u2049\u203C\u2122\u2139"  # misc that render as emoji
    "]"
)

# Slop vocabulary (§7.6). The plan names four words and one phrase; the rest are
# the same family and would read identically on a government page.
BANNED_WORDS = [
    "seamless", "seamlessly",
    "revolutionise", "revolutionize", "revolutionising", "revolutionizing",
    "unlock", "unlocking", "unleash",
    "elevate", "elevating",
    "ai-powered", "ai powered",
    "cutting-edge", "state-of-the-art",
    "game-changer", "game changer",
    "next-generation", "next-gen",
    "best-in-class", "world-class",
    "supercharge", "turbocharge",
    "delve", "dive into",
]

# Classes that cannot compile because a token was wiped, plus the ones the CSS
# gate catches. Catching them here gives a clearer error than a missing rule.
BANNED_CLASSES = [
    "rounded-2xl", "rounded-3xl", "rounded-full",
    "shadow-lg", "shadow-xl", "shadow-2xl",
    "backdrop-blur", "backdrop-filter",
    "bg-indigo-", "text-indigo-", "border-indigo-",
    "bg-purple-", "text-purple-", "border-purple-",
    "bg-violet-", "text-violet-", "from-violet-",
    "bg-blue-", "text-blue-", "from-blue-", "to-blue-",
    "bg-cyan-", "to-cyan-", "from-cyan-",
    "bg-slate-", "text-slate-",
    "bg-gray-", "text-gray-",
]

# The standing rules, checked as regressions (§3.2, S7). English identifiers only:
# Bangla prose about the programme is legitimate and is not matched here.
BANNED_IDENTIFIERS = ["district", "upazila"]

# §12.2 — Jinja autoescape everywhere; rich content goes through the sanitiser.
BANNED_TEMPLATE_TOKENS = [
    ("|safe", "|safe defeats autoescape (§12.2). Use the sanitised rich_text path."),
    ("<style", "<style> blocks are banned (S11). All CSS lives in source.css."),
    ("@apply", "@apply in templates is banned (S11)."),
    ("javascript:", "javascript: URLs are an XSS vector (§12.2)."),
]

# S3 — these columns must not exist on participants, at all.
PII_COLUMNS = [
    "phone", "email", "nid", "dob", "blood_group", "guardian_name",
    "photo_path", "photo", "signature", "birth_registration",
]

SCAN_SUFFIXES = {".py", ".html", ".jinja", ".jinja2", ".css", ".js", ".mjs", ".json", ".yml", ".yaml"}

SKIP_DIR_PARTS = {
    "node_modules", ".venv", "venv", ".git", "__pycache__", ".mypy_cache",
    ".ruff_cache", ".pytest_cache", "design-src", "docs", "tools",
    "migrations",  # autogenerated; Alembic writes its own strings
}

SKIP_FILENAMES = {"package-lock.json"}

# `|safe` is banned everywhere EXCEPT on the output of the rich-text sanitiser
# (§9.3 rule 3). That exception is real and unavoidable: sanitised HTML must be
# rendered as HTML. It is not free, so it costs two things:
#
#   1. the piped expression must be named `*_html`, which is the sanitiser's
#      contract — the value came through the bleach allowlist, not from a form;
#   2. the line must carry `check-bans:ignore <reason>`, so the exception is
#      visible in the diff and nobody has to guess whether it was intended.
#
# An earlier version banned `|safe` outright. It failed on the four legitimate
# uses and would have been switched off within a week — a gate nobody can satisfy
# is a gate nobody keeps. See SAFE_EXPR below.
SAFE_EXPR_RE = re.compile(r"\b\w+_html\s*\|\s*safe\b")

# GENERATED files. These are build output: Tailwind's own emitter legitimately
# contains the strings `rounded-full`, `backdrop-blur` and `backdrop-filter`
# whether or not a template uses them, so scanning them produces permanent false
# positives. The compiled sheet is policed by check-css.py instead.
GENERATED_PATH_PARTS = ("app/static/css/", "design-src/")
GENERATED_SUFFIXES = (".out.css", ".min.css", ".min.js")


@dataclass
class Violation:
    path: str
    line: int
    rule: str
    detail: str

    def __str__(self) -> str:
        return f"  {self.path}:{self.line}  {self.rule}\n      {self.detail}"


# ─────────────────────────────────────────────────────────────────────────────


def iter_files(roots: list[Path]) -> list[Path]:
    found: list[Path] = []
    for root in roots:
        if root.is_file():
            if _scannable(root):
                found.append(root)
            continue
        for p in sorted(root.rglob("*")):
            if p.is_file() and _scannable(p):
                found.append(p)
    return found


def _scannable(p: Path) -> bool:
    if p.suffix.lower() not in SCAN_SUFFIXES:
        return False
    if p.name in SKIP_FILENAMES:
        return False
    posix = p.as_posix()
    if any(part in posix for part in GENERATED_PATH_PARTS):
        return False
    if posix.endswith(GENERATED_SUFFIXES):
        return False
    return not any(part in SKIP_DIR_PARTS for part in p.parts)


def rel(path: Path, root: Path) -> Path:
    """Display path relative to the workspace, tolerating targets outside it."""
    try:
        return path.relative_to(root)
    except ValueError:
        return Path(os.path.relpath(path, root))


def force_utf8() -> None:
    """These tools print ‘§’ and Bangla. A cp1252 console mangles both, and a
    mangled message in a build log is worse than no message."""
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")  # type: ignore[union-attr]
        except (AttributeError, ValueError):
            pass


def strip_comments(text: str, suffix: str) -> str:
    """Blank out comments, preserving line numbers (non-newline → space).

    Comments are documentation. source.css explains at length WHICH classes are
    banned, and a checker that reads its own rulebook as a violation is a checker
    nobody will keep.
    """
    def blank(m: re.Match[str]) -> str:
        return re.sub(r"[^\n]", " ", m.group(0))

    if suffix == ".css":
        return re.sub(r"/\*.*?\*/", blank, text, flags=re.S)
    if suffix in {".js", ".mjs"}:
        text = re.sub(r"/\*.*?\*/", blank, text, flags=re.S)
        return re.sub(r"(?m)//[^\n]*", blank, text)
    if suffix in {".html", ".jinja", ".jinja2"}:
        text = re.sub(r"\{#.*?#\}", blank, text, flags=re.S)
        return re.sub(r"<!--.*?-->", blank, text, flags=re.S)
    if suffix in {".py", ".yml", ".yaml"}:
        return re.sub(r"(?m)^[ \t]*#[^\n]*", blank, text)
    return text


def is_ignored_file(text: str) -> bool:
    return "check-bans:ignore-file" in "\n".join(text.splitlines()[:5])


def check_encoding(raw: bytes, path: Path) -> list[Violation]:
    """S10 / R5 — a UTF-16 or BOM file has silently broken this repo before."""
    out = []
    if raw.startswith(b"\xef\xbb\xbf"):
        out.append(Violation(str(path), 1, "UTF-8 BOM",
                             "strip the BOM; reuse the LF/UTF-8 normalisation from S10"))
    elif raw.startswith(b"\xff\xfe") or raw.startswith(b"\xfe\xff"):
        out.append(Violation(str(path), 1, "UTF-16 encoded",
                             "re-save as UTF-8 without BOM — git treats UTF-16 as binary"))
    elif b"\x00" in raw[:8000]:
        out.append(Violation(str(path), 1, "NUL byte in a text file",
                             "re-save as UTF-8; this repo must never commit binary blobs"))
    return out


def check_text(text: str, path: Path) -> list[Violation]:
    rel = str(path)
    suffix = path.suffix.lower()
    is_template = suffix in {".html", ".jinja", ".jinja2"}
    is_python = suffix == ".py"
    out: list[Violation] = []

    for n, line in enumerate(text.splitlines(), 1):
        if "check-bans:ignore" in line:
            continue
        low = line.lower()

        for word in BANNED_WORDS:
            if word in low:
                out.append(Violation(rel, n, "banned vocabulary (§7.6)",
                                     f"“{word}” — {line.strip()[:110]}"))

        if m := EMOJI_RE.search(line):
            cp = f"U+{ord(m.group(0)):04X}"
            out.append(Violation(rel, n, "emoji as iconography (§7.6)",
                                 f"{cp} in: {line.strip()[:110]} — use app/static/img/sprite.svg"))

        for cls in BANNED_CLASSES:
            if cls in line:
                out.append(Violation(rel, n, "banned utility class (§7.6.1)",
                                     f"“{cls}” cannot compile or is banned — {line.strip()[:110]}"))

        # Arbitrary Tailwind value:  class="...bg-[#123456]..."  (§8.1 rule 1)
        if is_template and re.search(r'class\s*=\s*"[^"]*\[[^\]]+[^"]*"', line):
            out.append(Violation(rel, n, "arbitrary Tailwind value (§8.1 rule 1)",
                                 f"use a token instead — {line.strip()[:110]}"))

        if is_template:
            for token, why in BANNED_TEMPLATE_TOKENS:
                if token not in line:
                    continue
                # The one sanctioned `|safe`: sanitiser output, named `*_html`,
                # and explicitly marked. Anything else still fails.
                if token == "|safe" and SAFE_EXPR_RE.search(line):
                    continue
                out.append(Violation(rel, n, f"banned template token “{token}”", why))

        # Review marker left behind
        if "TODO" in line or "FIXME" in line:
            out.append(Violation(rel, n, "unresolved TODO/FIXME (§19.4)",
                                 line.strip()[:110]))

    # Identifier regressions (S7) — module-level only, so prose/comments are not
    # dragged in. A `district` column or route is what we are hunting.
    if is_python or is_template:
        for n, line in enumerate(text.splitlines(), 1):
            if "check-bans:ignore" in line:
                continue
            stripped = line.strip()
            if stripped.startswith("#") or stripped.startswith("{#"):
                continue
            for ident in BANNED_IDENTIFIERS:
                if re.search(rf"\b{ident}\b", stripped, re.I):
                    out.append(Violation(rel, n, f"removed dimension reintroduced ({ident})",
                                         f"S7 / §3.2 — one institution, no geography: {stripped[:110]}"))

    # S3 — prohibited participant columns
    if is_python and ("participants" in text or "people" in path.name):
        for n, line in enumerate(text.splitlines(), 1):
            if "check-bans:ignore" in line:
                continue
            for col in PII_COLUMNS:
                if re.search(rf"""mapped_column\(\s*[^)]*\b{col}\b|Column\(\s*[^)]*\b{col}\b|"{col}"\s*:""", line):
                    out.append(Violation(rel, n, f"prohibited participant column ({col})",
                                         f"S2/S3 — the schema must not be able to hold this: {line.strip()[:110]}"))

    return out


def main(argv: list[str] | None = None) -> int:
    force_utf8()
    parser = argparse.ArgumentParser(description="Ban-list gate (plan.md §7.6, §12.2).")
    parser.add_argument("paths", nargs="*", default=None,
                        help="files or directories (default: app/ and assets/)")
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args(argv)

    root = Path.cwd()
    roots = [Path(p) for p in args.paths] if args.paths else [root / "app", root / "assets"]
    roots = [r for r in roots if r.exists()]

    files = iter_files(roots)
    violations: list[Violation] = []
    scanned = 0

    for path in files:
        raw = path.read_bytes()
        violations += check_encoding(raw, rel(path, root))
        try:
            text = raw.decode("utf-8")
        except UnicodeDecodeError:
            continue  # already reported by check_encoding
        if is_ignored_file(text):
            continue
        scanned += 1
        violations += check_text(strip_comments(text, path.suffix.lower()), rel(path, root))

    if not args.quiet:
        print("check-bans:")
        print(f"  roots    {', '.join(str(rel(r, root)) for r in roots) or '(none)'}")
        print(f"  scanned  {scanned} file(s)")

    if violations:
        print(f"\n{len(violations)} violation(s):", file=sys.stderr)
        for v in violations:
            print(v, file=sys.stderr)
        return 1

    if not args.quiet:
        print("  OK — clean")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
